### PR TITLE
Added folder for Processing 3 adapted sketches

### PR DESCRIPTION
**Pull request by romanrandom**
pixeldrifter included

### CODE REVIEW

**Comment by tsulej** [comment]
do you plan to make more P3 versions?

**Comment by romanrandom** [comment]
When I need to use some I'll adapt them and add them to the folder. Although I'm not so sure about using a folder for that because if you make changes to the P2 versions they would have to be replicated in the P3 ones. Maybe it's better to create a P3 branch?

**Comment by tsulej** [comment]
I usually don't touch old scripts or changes are really minor. I such case I can maintain P3 version too in separate folder. But now I just include you PR.

**Comment by romanrandom** [comment]
OK. Really cool sketches BTW

**Comment by tsulej** [comment]
Thank you!

**Pull request merged**
